---
title: Trip Planning Resources
description: How do I plan my rides? Use this page to find out! 
author: Aseem Deodhar
date: 2023-01-20T00:00:00
slug: []
categories: []
tags: []
---

I first started getting into planning my bike rides beyond just - "Enter start and end points on Google Maps and GO!" after my [Bos/treal (check it out!!)](https://bostoncyclistsunion.org/bostreal) ride in 2021. Since then, I've gathered a list of resources which I have used, and some I haven't, but come recommended! **Note: None of the links are sponsored. I do not get any commission if you click on these links.**

To give an overview, the following points are a good gist of what to think of when trip planning. I have detailed each section further down as well. I am always happy to answer any questions you may have, and offer help, advice, and suggestions **at no monetary**. I was the recipient of all of this information because of generous help from others, and I wish that you get it at no cost as well!

-   Route Planning:
    -   Tools and Applications
    -   Distances & Hours
    -   Terrain
    -   Rest stops
-   Overnight Stops:
    -   Accommodation types
    -   Where to find them
-   Transportation to/from the ride:
    -   Rail & Bus
    -   Car
-   Gear & Packing List:
    -   Tools
    -   Navigation
    -   Refreshments
    -   Clothing
    -   Personal effects
-   Storage
-   Bike Transportation

## Route Planning:

A lot of thought goes into route planning. This is, after all the main component of the trip! I use multiple free and paid websites and tools to plan a route as thoroughly as possible. A few things to take note of are terrain & road conditions, rest stop locations, points of interest along the way, and sometimes when transportation options are limited, time to & from transportation points. We'll go through all of these.

### Websites and Applications

My route planning arsenal consists of two primary websites:

-   [RidewithGPS](https://ridewithgps.com/) (tiered pricing)
-   [Google Maps](https://www.google.com/maps/) (free)

I also use a website called [cycle.travel](https://cycle.travel/) sometimes. It is just like Google Maps, but directs you along bike friendly routes. I have found their routing suggestions to be better than Google Maps - especially in Europe. However, currently their service is only available in the usual suspects - Europe, North America and Australia-New Zealand.

Your route may be affected by your accommodation and transportation choices. Check out those sections for more information on how to plan for this. All these elements are, of course, dependent on each other, and may keep dynamically evolving depending on their availability and scheduling restrictions. Note that certain elements of RidewithGPS require a paid subscription. They offer multiple levels of subscriptions, so I'd recommend looking into what's important for you before purchasing anything.

Let's take an example trip from Newburyport MA to Portsmouth, NH. This route is relatively short at 24 miles, so we can do a day trip. As I live in Boston, I first need to find out how can I get to the starting point, and get back home from the end-point.

##### Getting to the Start Point

I know that there is a train from North Station in Boston to Newburyport. I go online to the [MBTA website and navigate to the Newburyport train schedule](https://www.mbta.com/schedules/CR-Newburyport/timetable). It looks like the first train leaves Boston at 5:30 am, and gets to Newburyport at 6:37 am. Perfect. We now know that the earliest we can start biking is at 6:37 am.

##### Getting to the End Point

As we have already decided to do this as a day-trip, we need to make sure that our return train or bus is on this day itself. I know that I can take either the C&J Bus from Portsmouth, or the Amtrak Downeaster train from Dover. I like trains more than buses! So we are taking the train back. I check the Since C&J pick me up from Portsmouth itself, I decide to go with that, and check its schedule on the C&J [website](https://www.ridecj.com/schedules/view-schedules/?departure=949&arrival=950). I see that there are buses every two hours on the hour - this means I could realistically take the 9 am bus - considering 2-1/2 hours for 24 miles. However, this would leave me with no time for sight-seeing, photographs, breaks, etc! And enjoyment is the most important part of a ride for me!

As such, this will depend on how much time you want to spend taking pictures, breaks, and do road/trail-side activities on the ride.

###### Travel Options in New England

Note that, there may be several different ways to get to & from your start point based on where you're thinking of going. As my personal experiences (on which this resource is built) are in and around Massachusetts, I will focus on those. Other services with bike-friendly transport options from Boston in various directions include [**Peterpan Bus lines**](https://peterpanbus.com/) (*Western MA and Cape Cod*), [**Dartmouth Coach**](https://dartmouthcoach.com/) (*towards Dartmouth College (Hanover NH) with stops along the way*), [**Concord Coach**](https://concordcoachlines.com/) (*extensive service in NH & ME*), [**C&J Bus lines**](https://www.ridecj.com/) (*Coastal NH & Tewksbury*), [**Plymouth & Brockton**](https://www.p-b.com/) (*South Shore MA and Cape Cod*), [**DATTCO**](https://www.dattco.com/bus-schedules/southcoast-boston-express-schedule/) (*MA South Coast*), [**Megabus**](https://us.megabus.com/) (*to Burlington VT*), and [**Amtrak**](https://www.amtrak.com/home) (*the Downeaster to Portland ME, and Northeast Regional towards NYC allow bikes on some services*). Note that some of these services might have limited and/or paid space for bikes that needs to be booked. From personal experience, Peterpan, Dartmouth Coach, Concord Coach have allowed my bike for free without reservations, whereas I had to buy space on Plymouth & Brockton and Amtrak.

###### New England Transportation Map

The MBTA has a really cool map showing regional transport services in New England on [their website](https://www.mbta.com/maps#:~:text=Maps-,Full%20System%20Map,-View%20full%20map). I have saved it [here as a PDF as well](route_planning/mbta_system_map/new_england_transport.pdf).

### Distances & Hours

This will be affected by your physical capacity, weather, road conditions and terrain. As a thumb-rule, I plan for 1 hour per 10 miles of riding. For rides with a hillier terrain, I add a one-hour break for every 3 hours of riding. This allows me to take breaks, account for slower speeds on climbs, etc.

### Terrain

You will either **choose** to go along a hilly road (views, destination after a climb, thrill of descent etc), or will **have** to - when the only usable route is along a hill. For example, crossing the Berkshire Hills, or the Green Mountains will almost always necessitate climbing hilly roads. You will *definitely* be rewarded with amazing views, and if your route involves a descent, the thrill of a speedy downhill ride.

Many hilly routes by way of being sparsely populated might not always be paved. Thicker tires and better suspension on your bike will make the ride much more comfortable.

### Rest stops

Rest stop locations for me primarily depend on two things: the terrain (hilly or not), and weather (too cold, too hot). I try to space my rest stops between 10 to 25 miles. Lower distances for hillier roads and bad weather conditions.

## Overnight Stops:

### Accommodation types

### Where to search for them

## Transportation to/from the ride:

### Rail & Bus

A lot of bus and rail services permit bikes on board. You may need to deconstruct the bike in various stages depending on the company. I have written a brief description of New England based transportation services' bicycle on-board policies above.

### Car

## Gear & Packing List:

### Tools

So far, I have been extremely lucky to have never had any mechanical issues with my bike while on a ride. I do however keep a few things on my on all rides where I will be away from the Boston Commuter rail area (ie easy transportation to home).

* A spare tube
* Patches + essential tools
* Small airpump

I recommend consulting this article on [Bikepacking.com](https://bikepacking.com/gear/bikepacking-repair-kit/) which is very thorough.


### Navigation

There is an abundance of navigation apps for your phone, or even standalone navigation computers. Based on your budget, you can spend between nothing to a few hundred dollars!

* Google Maps is of course excellent for navigation. However, despite its bicycle navigation capabilities having improved, there are better options available in the market. There is a limit to how much you can edit a particular route on Google Maps from its default suggestion.

* My personal favorite is RideWithGPS. As explained above, it is also very useful for designing routes to a very high degree of customization.

* Another app that is popular, but I haven't tried is Komoot.

* Bike computers are GPS devices where you can load in route files (.gpx files) and attach them to your bike handlebar. These display the route and also directions. An advantage of a bike computer is that it is relatively light with a much better battery life than using your phone. IMO, a phone with the RideWithGPS app and an external battery pack (I use a 13,000 mAh pack) is quite sufficient. A popular bike computer company is [Garmin](https://www.garmin.com/en-US/c/sports-fitness/cycling-bike-computers-bike-radar-power-meter-headlights/)

### Refreshments

*Carbs.*

*Electrolytes.*

These two are probably the most important nutritional requirements for your body during a long ride. Good, cheap, and light-weight sources to always have on your body are energy bars and gels. Electrolyte powders can be mixed in water, and energy drink brands such as Gatorade and Powerade are available in every gas station store, liquor store, and grocery/convenience store you will come across. *Please fill up your bottles with water whenever you get a chance*.

### Clothing

Clothing depends on the weather. In the summer, I prefer a light full-sleeved drifit cycling shirt. Longer sleeves help in warding off sun damage, help against mosquitoes on breaks, and can always be rolled up whenever needed. As the weather cools, I add multiple light layers instead of one or two thick layers.

For rides longer than 25-30 miles, I wear padded shorts. Padded shorts are to be worn without underwear. Yes. I know, it feels weird the first few times, but you'll get over it. It is so much better this way - trust me.

## Personal Gear Storage

I use four primary storage methods - 

* [Top Tube Bag](https://a.co/d/6imneQL) This is useful for keeping things such as a battery pack, keys, wallet, small items etc.

* [Bike Frame Bag](https://a.co/d/7NVMfBk) This is useful for a single overnighter ride where you might need to carry additional items such as toiletries, chargers, and a rolled up tshirt and underwear. Can also hold snack bars and electrolyte powder packets etc.

* [Pannier Bags](https://a.co/d/1p1tB7W) These come in various sizes and types, and are most useful if you're doing a 2+ day ride, or in cooler weather to keep extra layers. Also useful if you're hauling things to say a beach such as a beach chair, towel, picnic stuff!

* [Saddle Bag](https://a.co/d/7wGbPYw) This kind of bag goes under your 'saddle', or bike seat. I use it to carry my flat repair kit and multi-tool.